name: CMake-Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'

jobs:
  cmake_format:
    name: CMake-Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run CMake format
        run: |
          sudo pip3 install cmakelang
          ./.run-cmake-format
          output=$(git diff)
          if [ -n "$output" ]; then exit 1; else exit 0; fi
